### ISSUE TITLE
Getting an error socket.send() raised an exception.

### ISSUE THREAD

**Issue by stanlyjohn2** [python-websockets/websockets#1354]
````
def queue_consumer():
    print("Running Queue Consumer")
    while True:
        with config.connected_set_lock:
            connected_websockets = config.connected.copy()
        with config.data_queue_lock:
            try:
                while not config.data_queue.empty():
                    data = config.data_queue.get()
                    websockets.broadcast(
                        connected_websockets, json.dumps(data))
            except queue.Empty:
                print("queue empty")
            except Exception as e:
                # Handle the exception
                print(f"Exception occurred during broadcast: {e}")
        print("Waiting for interval", INTERVAL)
        sleep(INTERVAL)
````

For the above code, it is running fine for few hours, but after that, getting an error "socket.send() raised an exception." continously. And it is not printing the broadcast exception, which we are trying to catch in the above code. Why this might be happening?

**Comment by aaugustin** [comment]
It's a bit difficult to help because you didn't provide the stack trace or logs.

Do you see `skipped broadcast: failed to write message`? I suspect that you do. Then it's just logging.

If you want to get an exception when a connection becomes unavailable, use `broadcast(..., raise_exceptions=True)`.

Check the docs: https://websockets.readthedocs.io/en/stable/reference/asyncio/server.html#websockets.broadcast

You can also read the documentation about configuring logging and how broadcast is designed.
