### ISSUE TITLE
URI "ws" scheme not working

### ISSUE THREAD

**Issue by lhcunha** [python-websockets/websockets#1359]
When I run the following code:
```
async def connect_to_websocket(url, token):
    headers = {
        "Authorization": f"Bearer {token}"
    }
    
    
    async with websockets.connect(url, extra_headers=headers) as websocket:
        while True:
            # Perform WebSocket operations here
            message = await websocket.recv()
            print("Received message:", message)

url = "ws://10.48.209.11/kafkacomet/socket/websocket"
#token = get_token()
token = "any_token"
asyncio.run(connect_to_websocket(url, token))
```

I get the following error:
`File "C:\Python311\Lib\site-packages\websockets\uri.py", line 77, in parse_uri
    raise exceptions.InvalidURI(uri, "scheme isn't ws or wss")
websockets.exceptions.InvalidURI: https://10.48.209.11/kafkacomet/socket/websocket isn't a valid URI: scheme isn't ws or wss`

I'm using the "ws" scheme but the error prints that Im using "https". Is this a bug?

When I change "ws" to "wss" it works.

**Comment by aaugustin** [comment]
I suspect this is because you make a non-TLS connection and get a 3xx redirect with `Location: https://10.48.209.11/kafkacomet/socket/websocket`.

Could you enable debug logs and provide them to confirm this hypothesis? See here: https://websockets.readthedocs.io/en/stable/topics/logging.html#configure-logging

I'm not sure there's a spec about the expected behavior of redirects of websocket connections. We could probably translate `https://` to `ws://`. First, I would like to check for any security concerns with this.

**Comment by aaugustin** [comment]
The current behavior of websockets is consistent with the behavior of browsers. Therefore, I will not change it.

I tested with this script:

```python
#!/usr/bin/env python

import asyncio
import http
import websockets

async def redirect(path, request_headers):
    if path == "/redirect":
        return http.HTTPStatus.TEMPORARY_REDIRECT, [
            ("Location", "http://localhost:8765"),
        ], b""

async def echo(websocket):
    async for message in websocket:
        await websocket.send(message)

async def main():
    async with websockets.serve(
        echo, "localhost", 8765,
        process_request=redirect,
    ):
        await asyncio.Future()  # run forever

asyncio.run(main())
```

Then, I try to connect to `ws://localhost:8765/redirect` in the browser's console.

**Chrome**

```
new WebSocket("ws://localhost:8765/redirect")
WebSocket {url: 'ws://localhost:8765/redirect', readyState: 0, bufferedAmount: 0, onopen: null, onerror: null, …}
VM33:1 WebSocket connection to 'ws://localhost:8765/redirect' failed: 
(anonymous) @ VM33:1

new WebSocket("ws://localhost:8765/")
WebSocket {url: 'ws://localhost:8765/', readyState: 0, bufferedAmount: 0, onopen: null, onerror: null, …}
```

**Firefox**

```
new WebSocket("ws://localhost:8765/redirect")
WebSocket { url: "ws://localhost:8765/redirect", readyState: 0, bufferedAmount: 0, onopen: null, onerror: null, onclose: null, extensions: "", protocol: "", onmessage: null, binaryType: "blob" }
Firefox can’t establish a connection to the server at ws://localhost:8765/redirect. debugger eval code:1

new WebSocket("ws://localhost:8765/")
WebSocket { url: "ws://localhost:8765/", readyState: 0, bufferedAmount: 0, onopen: null, onerror: null, onclose: null, extensions: "", protocol: "", onmessage: null, binaryType: "blob" }
```

If I change the redirect URI from `http://localhost:8765` to `ws://localhost:8765` in the test script, connecting to `ws://localhost:8765/redirect` works.

**Comment by aaugustin** [comment]
(Deleted my previous comment because my testing was invalid.)

Browsers generally don't support redirects on WebSocket connections, even if you redirect to a `ws://` URL rather than a `http://` URL. This makes redirects quite useless in general.

I believe that the current behavior is reasonable. I don't see evidence for changing it.
