### ISSUE TITLE
Does websockets library support http connection pool or session?

### ISSUE THREAD

**Issue by wenleix** [python-websockets/websockets#1361]
Hi,

Some HTTP library like aiohttp supports connection reuse via client session (https://docs.aiohttp.org/en/stable/client_reference.html#client-session). So recently TCP connection may be reused if many connections are closed and recreated frequently in a short period of time.

I am wondering if websockets library supports this? Quickly browse the doc seems the singleton API `websockets.client.connect` (https://websockets.readthedocs.io/en/stable/reference/asyncio/client.html#websockets.client.connect) is the most common way to establish connection. But just want to check if I am missing anything obviously. 

Thanks!

**Comment by aaugustin** [comment]
websockets doesn't support this feature because it makes little sense for WebSocket connections, which are long lived. (It does make sens for HTTP connections.)

Furthermore, the spec requires closing the TCP connection when closing the WebSocket connection. So implementing that behavior in websockets would be a spec violation.
