### ISSUE TITLE
Behaviour of websockets sansI/O Layer when the connection fails

### ISSUE THREAD

**Issue by gourav-kandoria** [python-websockets/websockets#1397]
When the data is received using below method:
        self.conn.receive_data(data)
 There are some scenarios(like the size of msg received is more that configured, data received not correct according to websockets specs) where the connections fails, in this scenario, What if there is some exception like ConnectionFailedException which can be  thrown when the connection fails.
so that appropriate next step can be taken.

For example, something like this
```
try
    self.conn.receive_data(data)
except ConnectionFailException:
    output = self.conn.data_to_send()
    self.transport.writelines(output)
    self.transport.close()
    # have access to a close code here
    # which can be sent to asgi app in disconnect event
```

**Comment by aaugustin** [comment]
`receive_data` doesn't raise exceptions (other than `EOFError` if you called `receive_eof` before, which would be a bug.)

If you give websockets invalid inputs, websockets will close the connection, which you will see because `data_to_send` will contain the end-of-stream marker `b""`.

If you want to tell what happened, check the [close_exc](https://websockets.readthedocs.io/en/stable/reference/sansio/server.html#websockets.server.ServerProtocol.close_exc) attribute.

The implementation is designed like this because it's usually a background task/thread reading from the socket and feeding data to websockets with `receive_data` and there's no convenient way to surface exceptions from there.

**Comment by aaugustin** [comment]
To illustrate this, the threading-based implementation in websockets (which runs on top of the Sans-I/O layer) calls `receive_data` without handling exceptions here: https://github.com/python-websockets/websockets/blob/adfb8d69a7a1f6f4c8381c9e7182619d202c3cf2/src/websockets/sync/connection.py#L556

I'm not THAT confident in my ability to write such complex code correctly so I have a catch-all exception handler - https://github.com/python-websockets/websockets/blob/adfb8d69a7a1f6f4c8381c9e7182619d202c3cf2/src/websockets/sync/connection.py#L608-L609 - but I don't expect it to run.

**Comment by gourav-kandoria** [comment]
That's understandable but let's say after calling receive data. i am able to detect which was the error which caused to fail the connection like below
  self.conn.receive_data(data)
  if self.conn.parser_exc is not None:
     .....
  
  then we might want to send close frame to the client for some errors like payloadsize is bigger than server can process.
  but we don't get the byte data for that close using data_to_send.
  
  I guess, in these situation when parser_exc is set to something and when connection is failed. 
  The fail should not proceed to close the connection.
  
  Now I guess, it should be the responsibility of the code using this sansI/O layer to 
  Firstly call send_close() method
  and then call data_to_send() method to receive data to write to transport.
