### ISSUE TITLE
sdist is missing tests

### ISSUE THREAD

**Issue by mtelka** [python-websockets/websockets#1426]
The sdist package at PyPI is missing tests.  Please add tests to sdist to make downstream testing easier.  Thank you.

**Comment by aaugustin** [comment]
I am not including tests in sdists because it they aren't needed for the use case of installing websockets, which is the majority use case. I will not change that.

I know that distro maintainers usually want to run the tests but that doesn't help me. On the contrary, it generates discussions that don't improve websockets.

(I'm familiar with the tension between library maintainers and distro maintainers; no need to redo the whole debate :-) There've been similar discussions in this bug tracker before.)

My deliverables for downstream usage (production / packaging) are:

- the code
- the docs

Everything else (test suite, benchmarking scripts, etc.) is only for contributing to websockets and only available in the git repository. If you want to download the entire repository at a specific tag, GitHub provides tarballs.
