### ISSUE TITLE
The docs for websockets.sync.Connection.recv are not rendered correctly in VSCode

### ISSUE THREAD

**Issue by plorgai-ta** [python-websockets/websockets#1526]
The [docs for the `recv` function](https://github.com/python-websockets/websockets/blob/e5182c95a3332535a034c409d59463afbd760f0c/src/websockets/sync/connection.py#L194-L196
) are not rendered correctly in VSCode. See the screenshot.

<img width="1071" alt="Screenshot 2024-10-18 at 2 22 14 PM" src="https://github.com/user-attachments/assets/fda333e4-2b9f-4217-9f66-e5ba6e9f52d3">

I'm not familiar with how the doc strings are written, but it appears that VSCode thinks the `A` is a variable name of what is returned, and is wrapping the rest of the text underneath as a description. I think it is expecting a variable name followed by a colon, which is what we see in the `Raises` section.

It also doesn't render the `Text_` or `Binary_` strings at all. These look like they are replaced by the links just below, but I'm not sure.

**Comment by aaugustin** [comment]
Thank you for reporting this problem.

Probably this is because VS Code doesn't understand the style of docstrings used by the project, namely https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

I want to stick to that style. I wish I could help but I don't see anything I can do. This looks more like a VS Code <> Napoleon problem than a websockets problem.
