### ISSUE TITLE
TypeError: websockets.asyncio.messages.Assembler() argument after * must be an iterable, not NoneType

### ISSUE THREAD

**Issue by Joshuaalbert** [python-websockets/websockets#1540]
After updating to version 14.0 I get this `TypeError: websockets.asyncio.messages.Assembler() argument after * must be an iterable, not NoneType`. Did version 14 change the API?

```python
import asyncio

import uvloop
import websockets

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

HEART_BEAT_INTERVAL = 10  # Replace with your desired heartbeat interval


async def connect():
    async for websocket in websockets.connect(
            uri="wss://...",
            max_queue=None,
            ping_interval=60,
            ping_timeout=60
    ):
        try:
            while True:
                try:
                    message = await asyncio.wait_for(websocket.recv(), timeout=HEART_BEAT_INTERVAL)
                    print(message)
                except asyncio.TimeoutError:
                    print("Timeout, no message received")
                    continue
        except websockets.ConnectionClosed:
            continue
        except asyncio.CancelledError:
            break


if __name__ == '__main__':
    asyncio.run(connect())
```

Full traceback

```
File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/albert/git/crypto_loops/CryptoLoops/debug/uvloop_error.py", line 12, in connect
    async for websocket in websockets.connect(
  File "/home/albert/miniconda3/envs/cyrpto_loops_py/lib/python3.11/site-packages/websockets/asyncio/client.py", line 500, in __aiter__
    async with self as protocol:
  File "/home/albert/miniconda3/envs/cyrpto_loops_py/lib/python3.11/site-packages/websockets/asyncio/client.py", line 484, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/home/albert/miniconda3/envs/cyrpto_loops_py/lib/python3.11/site-packages/websockets/asyncio/client.py", line 441, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albert/miniconda3/envs/cyrpto_loops_py/lib/python3.11/site-packages/websockets/asyncio/client.py", line 367, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 2084, in create_connection
  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection
  File "uvloop/handles/stream.pyx", line 1007, in uvloop.loop.__uv_stream_buffered_on_read
  File "uvloop/loop.pyx", line 109, in uvloop.loop.run_in_context1
  File "uvloop/sslproto.pyx", line 379, in uvloop.loop.SSLProtocol.buffer_updated
  File "uvloop/sslproto.pyx", line 505, in uvloop.loop.SSLProtocol._do_handshake
  File "uvloop/sslproto.pyx", line 541, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "/home/albert/miniconda3/envs/cyrpto_loops_py/lib/python3.11/site-packages/websockets/asyncio/connection.py", line 961, in connection_made
    self.recv_messages = Assembler(
                         ^^^^^^^^^^
TypeError: websockets.asyncio.messages.Assembler() argument after * must be an iterable, not NoneType
```

This is with `uvloop==0.17.0`.

**Comment by aaugustin** [comment]
The full story is:

- The initial implementation of websockets (like 10 years ago) contained an unbounded queue of incoming messages.
- In #105, I learned that this broke flow control for incoming messages i.e. websockets never stops reading from the network, no matter how much data is already buffered and available for recv(). So I merged PR #106, adding a limit to the queue of incoming messages and proper flow control. This was in version 3.1. The implementation made it possible to disable the limit by setting `max_queue=0`. The documentation mentioned that innocently.
- I dislike the semantics of `max_queue=0` — we're writing Python, not C — so I changed it to `max_queue=None` in 8.0.
- I didn't support that case in the new asyncio implementation, which is the default since 14.0. See the links in the previous message for details.

Today, I'm questioning whether websockets should support `max_queue=None`, for the following reasons:

- This is literally  declaring "I'd rather crash with `MemoryError` than stop reading from the network". Look, if you crash with `MemoryError`, you aren't going to read much more from the network anyway...
- I don't believe that most engineers configuring `max_queue=None` truly understand backpressure and have a good reason to set it that way. If they understood backpressure, they'd know why it mustn't be `None`.
- The counter argument is that some users may know that 16 is too small, not care much about their program running out of memory, and not want to spend time thinking about the proper value. `max_queue=None` isn't that different from `max_queue=1_000_000` in that case, though.

So, the range of options for fixing this include:

1. Document the difference in the upgrade guide. Don't change the code. This is correct in theory; in practice it will annoy many users whose code never encountered conditions where a proper `max_size` matters.
2. Document the difference in the upgrade guide. Turn None into 2 ** 20 (or something similarly large) with a `DeprecationWarning`. At least this prevents a crash but it's just as annoying as option 1.
3. Implement `max_size = None`, discourage it in the docs, and forget about it.

**Comment by aaugustin** [comment]
I'm weakly leaning towards 3 because I don't want to be a purist on a mission to educate users on backpressure. In many low-volume use cases, you can use websockets without backpressure and you'll never run in trouble.

**Comment by aaugustin** [comment]
Also it makes for a smoother migration to the new asyncio implementation.

**Comment by aaugustin** [comment]
FYI: I'm planning to wait a few days for other reports of incompatibilities between the legacy and new implementation, then I'll make a release with that fix.

**Comment by aaugustin** [comment]
PS: don't do crypto. (That `cyrpto_loops_py` in the path to your env is suspicious.)

**Comment by Joshuaalbert** [comment]
Thanks for the replies. It's encouraging to see such swift attention. Can you explain how setting a maximum queue size on the receiver side imposes backpressue? I probably don't understand, but isn't that a local constraint? I.e. you're not signalling to the source to slow down. It would just close the connection if breached, leading to loss of consistency in the stream. If you have a variable load but you can handle all of it even at peak, then the queue size seems less useful.  ps. nothing wrong with cryptos.

**Comment by aaugustin** [comment]
It wouldn't close the connection; it would just pause reading from the network until your app has caught up.
