### ISSUE TITLE
Is there a way to catch handshake exceptions

### ISSUE THREAD

**Issue by juaoose** [python-websockets/websockets#1561]
I'm setting up a simple alarm system and noticed some `InvalidUpgrade` errors which seem to come from bots. After looking at the error, it looks like I'm not able to catch the `InvalidUpgrade` exception anywhere in my code... the best I was able to achieve was change the error by raising or returning a BAD_REQUEST in `process_request`...

Is there a way to make handshake exceptions raise up to the caller of `serve` or `unix_serve`? (I could silence these using a `logging` filter, but still wondering)

I'm using version the "new asyncio" version.

```
opening handshake failed
Traceback (most recent call last):
  File "/root/development/loopy/server/venv/lib/python3.12/site-packages/websockets/asyncio/server.py", line 358, in conn_handler
    await connection.handshake(
  File "/root/development/loopy/server/venv/lib/python3.12/site-packages/websockets/asyncio/server.py", line 209, in handshake
    raise self.protocol.handshake_exc
  File "/root/development/loopy/server/venv/lib/python3.12/site-packages/websockets/server.py", line 139, in accept
    ) = self.process_request(request)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/development/loopy/server/venv/lib/python3.12/site-packages/websockets/server.py", line 240, in process_request
    raise InvalidUpgrade(
websockets.exceptions.InvalidUpgrade: missing Connection header
```

**Comment by aaugustin** [comment]
There's no good way to do that: indeed, it would interrupt `serve`, exiting the server thus preventing it from servicing future connections. That's why exceptions are logged rather than raised. Look up "inversion of control" for more theory on this.

I believe that this exception is raised at the WARNING level. (If not, that's a problem.) If you're getting too much noise, I recommend that you configure logging to log only at the level ERROR or above.

If you don't want to do that, dealing with frequent cases in `process_request` is a good alternative. Perhaps you can do it in `process_response` as well. However, I'm afraid this will be a rabbit hole because you're facing Internet background noise...

**Comment by juaoose** [comment]
@aaugustin Makes sense, I believe tweaking logging is the way to go for my case. Thank you!

**Comment by vanous** [comment]
For those who land here searching for a solution to the internet background noise, logger filter is one way to solve this while keeping logging:

```python
level = logging.DEBUG

logger = logging.getLogger("websockets")
logger.setLevel(level)

class SkipWebsocketEOFFilter(logging.Filter):
    def filter(self, record):
        return not any(
            x.lower() in record.getMessage().lower()
            for x in ["opening handshake failed", "invalid upgrade"]
        )

console_handler = logging.StreamHandler()
console_handler.setLevel(level) 

#logger.addFilter(SkipWebsocketEOFFilter()) # this should work but it doesn't, thus add the filter to the handler:
console_handler.addFilter(SkipWebsocketEOFFilter())
```
